### ISSUE TITLE
subject.disassociate_media doesn't work for media with consensus

### ISSUE THREAD

**Issue by CogniacViSean** [Cogniac/cogniac-sdk-py#130]
Trying to remove some consensus media associations via the SDK, but the subject.disassociate_media call does not remove consensus associations. For example, after running this code: 

```
cc = cogniac.CogniacConnection(tenant_id='3qn5hdqo9760')
subject = cc.get_subject('ocr_text_2uryw')
subject.disassociate_media('K7IBJSKUQUEEITUJBS3V5YN1PWA4')
```

The following still returns True, indicating this media is still in the subject's consensus associations:

```
'K7IBJSKUQUEEITUJBS3V5YN1PWA4' in {assoc['media']['media_id'] for assoc in subject.media_associations(consensus='True')}
```

**Comment by ymtsang** [comment]
Because it has focus in the association, to disassociate the media in SDK, you need to also specify the focus. For example, for the same media,

<img width="576" alt="Screen Shot 2022-10-07 at 11 27 12 AM" src="https://user-images.githubusercontent.com/19434101/194625593-15e3bcbe-6aac-45e9-8c99-50d421c4d9c0.png">

```
subject.disassociate_media('K7IBJSKUQUEEITUJBS3V5YN1PWA4', focus={'box': {'x0':0, 'y0': 742, 'x1': 46, 'y1': 742+66}})
```
Then, the association is gone.
<img width="911" alt="Screen Shot 2022-10-07 at 11 30 00 AM" src="https://user-images.githubusercontent.com/19434101/194625517-d203d962-ba84-4426-8aad-3d41a8e2e7cd.png">

**Comment by CogniacViSean** [comment]
This worked, hadn't tried this for consensus with focus before, thanks Ming!
